Adam-Kulju/Patricia

engine/src/defs.h

Fix missing array include. For some reason this works without the include on mingw, even though I don't think it should. Doesn't work on native windows compile.

Fix missing include.

---

engine/src/defs.h
engine/src/position.h
engine/src/search.h
engine/src/utils.h

TT entries are now 12 byte wide instead of 16
Bench 8320422

More TT entries

---

engine/src/nnue.h
engine/src/position.h

Elo   | 7.44 +- 3.86 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=16MB
LLR   | 2.97 (-2.94, 2.94) [0.00, 3.00]
Games | N: 10596 W: 3184 L: 2957 D: 4455
Penta | [145, 1055, 2727, 1170, 201]
https://chess.swehosting.se/test/7921/
Bench: 5602795

Fused updates

---

engine/src/uci.h

Until now, there was a bug that by running "go nodes x" and then "go depth 20", the nodes limit would remain
Bench 5602795

Disable nodes limit unless specified again

---

engine/src/search.h

Elo   | 7.01 +- 3.59 (95%)
SPRT  | 60.0+0.60s Threads=1 Hash=128MB
Games | N: 10316 W: 2825 L: 2617 D: 4874
Penta | [71, 1102, 2593, 1332, 60]
https://chess.swehosting.se/test/8049/
Bench: 7498607

reduce sbeta margin

---

engine/src/search.h
engine/src/tm.h

Bench: 7341237
Elo   | 4.23 +- 2.72 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 20138 W: 5635 L: 5390 D: 9113
Penta | [230, 2161, 5083, 2324, 271]
https://chess.swehosting.se/test/8110/

bestmove stability

---

engine/src/search.h

Bench: 6795207
Elo   | 4.31 +- 2.81 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 3.00]
Games | N: 20872 W: 5899 L: 5640 D: 9333
Penta | [298, 2348, 4926, 2525, 339]
https://chess.swehosting.se/test/8157/

reset next killer at start of moveloop

---

engine/src/search.h

Bench: 5813201
Elo   | 6.61 +- 3.64 (95%)
Games | N: 12358 W: 3495 L: 3260 D: 5603
Penta | [164, 1380, 2882, 1563, 190]
https://chess.swehosting.se/test/8388/

return average of eval and beta in rfp

---

engine/datagen/datagen.cpp
engine/src/search.h
engine/src/utils.h

Elo   | 2.17 +- 2.48 (95%)
LLR   | 2.95 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 21280 W: 5725 L: 5592 D: 9963
Penta | [183, 2204, 5739, 2325, 189]
https://chess.swehosting.se/test/8440/

Simplify bestmoves

---

engine/src/search.h

Bench: 5375006
Elo   | 5.29 +- 3.25 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 3.00]
Games | N: 17740 W: 5241 L: 4971 D: 7528
Penta | [353, 1987, 3963, 2171, 396]
https://chess.swehosting.se/test/8484/

reduce depth on fail high

---

engine/src/search.h

Elo   | 12.43 +- 5.01 (95%)
Games | N: 5704 W: 1153 L: 949 D: 3602
Penta | [50, 559, 1454, 715, 74]
https://chess.swehosting.se/test/9557/

a more balanced material scale impl

---

engine/src/search.h

Bench: 4606731
Elo   | 2.12 +- 1.68 (95%)
Games | N: 53176 W: 10571 L: 10246 D: 32359
Penta | [593, 6031, 13048, 6290, 626]
https://chess.swehosting.se/test/9576/

history pruning

---

engine/src/search.h

Bench: 5168891
Elo   | 5.55 +- 3.25 (95%)
Games | N: 14514 W: 2978 L: 2746 D: 8790
Penta | [153, 1631, 3495, 1787, 191]
https://chess.swehosting.se/test/9584/

search deeper if we found a great move

---

engine/src/search.h

Bench: 5603318
Elo   | 3.57 +- 2.44 (95%)
Games | N: 24360 W: 4518 L: 4268 D: 15574
Penta | [264, 2596, 6230, 2806, 284]
https://chess.swehosting.se/test/9910/

increase hist bonus if we crushed beta

---

engine/src/search.h

Bench: 4194283
Elo   | 8.95 +- 4.22 (95%)
LLR   | 2.94 (-2.94, 2.94) [0.00, 3.00]
Games | N: 8194 W: 1564 L: 1353 D: 5277
Penta | [72, 864, 2045, 1013, 103]
https://chess.swehosting.se/test/9914/

do shallower

---

engine/src/search.h

Elo   | 3.12 +- 2.14 (95%)
SPRT  | 60.0+0.60s Threads=1 Hash=128MB
Games | N: 24804 W: 3837 L: 3614 D: 17353
Penta | [118, 2463, 7020, 2680, 121]
https://chess.swehosting.se/test/9933/
Bench: 4155116

triple ext

---

engine/src/search.h

Elo   | 2.33 +- 1.79 (95%)
Games | N: 43278 W: 7610 L: 7320 D: 28348
Penta | [393, 4724, 11158, 4928, 436]
https://chess.swehosting.se/test/9997/

remove negative reductions

---

engine/src/search.h

Elo   | 1.52 +- 3.21 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 13460 W: 2331 L: 2272 D: 8857
Penta | [120, 1481, 3486, 1506, 137]
https://chess.swehosting.se/test/10257/

Clean up lmr!

---

engine/src/search.h

Elo   | 3.84 +- 2.54 (95%)
Games | N: 21652 W: 3917 L: 3678 D: 14057
Penta | [203, 2306, 5589, 2505, 223]
https://chess.swehosting.se/test/10259/

ttdepth in lmr

---

engine/src/search.h

Bench: 4207235
Elo   | 14.77 +- 5.50 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 3.00]
Games | N: 4944 W: 1033 L: 823 D: 3088
Penta | [40, 499, 1220, 637, 76]
https://chess.swehosting.se/test/10361/

fix corrhist

---

engine/src/search.h

Bench: 4556505
Elo   | 2.36 +- 1.81 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 42638 W: 7476 L: 7186 D: 27976
Penta | [418, 4562, 11099, 4792, 448]
https://chess.swehosting.se/test/10364/

reduce reduction if move is a check

---

engine/src/search.h
engine/src/utils.h

Bench: 3285890
Elo   | 2.94 +- 2.11 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 3.00]
Games | N: 31110 W: 5478 L: 5215 D: 20417
Penta | [294, 3314, 8097, 3535, 315]
https://chess.swehosting.se/test/10488/

increase reduction if lots of fail highs

---

engine/src/search.h

Bench: 3304211
Elo   | 1.56 +- 1.25 (95%)
Games | N: 89930 W: 15889 L: 15486 D: 58555
Penta | [928, 9748, 23191, 10189, 909]
https://chess.swehosting.se/test/10873/

change improving

---

engine/src/search.h

Elo   | 1.62 +- 1.29 (95%)
LLR   | 3.02 (-2.94, 2.94) [0.00, 3.00]
Games | N: 81350 W: 14124 L: 13745 D: 53481
Penta | [734, 8725, 21438, 8984, 794]
https://chess.swehosting.se/test/11008/

More lmrdepth

---

engine/src/uci.h

Bench: 3296690
Elo   | 2.31 +- 1.77 (95%)
Games | N: 40604 W: 7234 L: 6964 D: 26406
Penta | [312, 4141, 11141, 4381, 327]
https://chess.swehosting.se/test/12036/

increase maximum time to 80% of remaining time
