engine/src/params.h, engine/src/patricia.cpp, engine/src/position.h, engine/src/search.h
Score of patricia-dev vs patricia_base: 181 - 104 - 121  [0.595] 406
...      patricia-dev playing White: 79 - 57 - 67  [0.554] 203
...      patricia-dev playing Black: 102 - 47 - 54  [0.635] 203
...      White vs Black: 126 - 159 - 121  [0.459] 406
Elo difference: 66.7 +/- 28.6, LOS: 100.0 %, DrawRatio: 29.8 %
SPRT: llr 2.97 (100.9%), lbound -2.94, ubound 2.94 - H1 was accepted
=> LMR (also fix rfp file failure from before)

engine/src/movegen.h, engine/src/patricia.cpp, engine/src/search.h, engine/src/uci.h, engine/src/utils.h
Score of patricia-dev vs patricia_base: 64 - 7 - 28  [0.788] 99
...      patricia-dev playing White: 34 - 5 - 11  [0.790] 50
...      patricia-dev playing Black: 30 - 2 - 17  [0.786] 49
...      White vs Black: 36 - 35 - 28  [0.505] 99
Elo difference: 228.0 +/- 65.0, LOS: 100.0 %, DrawRatio: 28.3 %
SPRT: llr 2.95 (100.3%), lbound -2.94, ubound 2.94 - H1 was accepted
=> history heuristic

engine/src/search.h, engine/src/utils.h
=> print full pv

engine/src/params.h
no functional change
bench 7280976
=> Fix Missing Include

engine/src/params.h, engine/src/search.h
Bench: 7635940
Elo   | 25.90 +- 9.79 (95%)
SPRT  | 60.0+0.60s Threads=1 Hash=128MB
Games | N: 2688 W: 845 L: 645 D: 1198
Penta | [15, 244, 655, 386, 44]
http://localhost:8000/test/30/
=> 5k iters of LTC SPSA

engine/src/defs.h, engine/src/search.h, engine/src/utils.h
Only store 16 bit for the position hash security check
=> Shrink TT entries even more

engine/src/position.h, engine/src/search.h
=> Faster repetition detection

engine/src/nnue.h, engine/src/position.h, engine/src/search.h, engine/src/uci.h
=> Faster accumulator updates

engine/src/search.h
=> Tweak tt move replacement strategy

engine/src/search.h
=> Tighter aspiration windows

engine/src/search.h
=> Tweak histories updating

engine/src/search.h
=> add root and matescore conditions

engine/src/search.h
=> Don't recalculate in_check

engine/src/search.h
=> Don't erase static_eval on ss_push

engine/src/search.h
=> add cutnodes

engine/src/search.h
=> remove the deadweight bonus1

engine/src/defs.h, engine/src/search.h, engine/src/utils.h
=> Save static eval in TT

engine/src/defs.h, engine/src/search.h, engine/src/utils.h
=> Refactor TT (non functional)

engine/datagen/datagen.cpp, engine/src/defs.h, engine/src/patricia.cpp, engine/src/position.h, engine/src/search.h, engine/src/uci.h
=> Separate legality check from make_move

engine/src/search.h
=> Shrink usage of game_hist

engine/datagen/datagen.cpp, engine/src/defs.h, engine/src/params.h, engine/src/search.h, engine/src/utils.h
=> Implement TT buckets

engine/src/search.h
=> Keep track of PV nodes from a (template) parameter

engine/datagen/datagen.cpp, engine/src/search.h, engine/src/utils.h
=> lil refactor

engine/src/defs.h, engine/src/movegen.h, engine/src/position.h
=> Make a get_piece_type() function

engine/datagen/datagen.cpp, engine/src/defs.h, engine/src/movegen.h, engine/src/patricia.cpp, engine/src/position.h, engine/src/search.h
=> Towards only 64 board

engine/src/bitboard.h, engine/src/defs.h, engine/src/movegen.h, engine/src/nnue.h, engine/src/position.h
=> See rewrite 2

engine/src/patricia.cpp, engine/src/position.h, engine/src/search.h, engine/src/uci.h
=> Easier perft interface

engine/src/bitboard.h, engine/src/movegen.h
Elo   | 36.96 +- 8.89 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 2038 W: 675 L: 459 D: 904
Penta | [18, 163, 465, 331, 42]
https://chess.swehosting.se/test/8320/
Bench: 6149081
=> it's so over

engine/datagen/datagen.cpp, engine/src/bitboard.h, engine/src/defs.h, engine/src/movegen.h, engine/src/nnue.h, engine/src/position.h, engine/src/search.h, engine/src/utils.h
=> mailbox is dead.

engine/src/search.h
=> Sacrifice the roooook

engine/datagen/datagen.cpp, engine/src/bitboard.h, engine/src/movegen.h, engine/src/position.h, engine/src/search.h
Elo   | 13.16 +- 5.38 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=16MB
LLR   | 3.03 (-2.94, 2.94) [0.00, 3.00]
Games | N: 6260 W: 1879 L: 1642 D: 2739
Penta | [101, 664, 1402, 823, 140]
https://chess.swehosting.se/test/8377/
=> check masks in movegen

engine/src/bitboard.h, engine/src/position.h
=> Fast islegal

engine/src/search.h
=> Tweak asp window

engine/src/defs.h, engine/src/movegen.h, engine/src/position.h, engine/src/uci.h
=> move type speedup

engine/datagen/datagen.cpp, engine/src/movegen.h, engine/src/position.h, engine/src/search.h, engine/src/utils.h
=> Cleaner root moves and multipv

engine/src/search.h
=> dont save exact entries in qsearch

engine/src/search.h
=> does exactly what you think it does

engine/src/nnue.h, engine/src/search.h
- Fix compilation on gcc
- Don't save exact entries from QS
- Raise alpha in standpat
Bench 5164782
=> Good stuff

engine/src/patricia.cpp, engine/src/search.h, engine/src/uci.h, engine/src/utils.h
=> Threadpool

engine/src/search.h, engine/src/uci.h, engine/src/utils.h
fix threading bug where the threads would slam CPU on the opponent's time
=> goodness that was awful

engine/src/search.h
=> fix SMP bug

engine/src/search.h, engine/src/uci.h
=> support setting only one value

engine/src/search.h
=> switch to solid net when worse

engine/datagen/datagen.cpp, engine/src/search.h
Elo   | 4.01 +- 6.16 (95%)
LLR   | 3.15 (-2.94, 2.94) [-10.00, 0.00]
Games | N: 2860 W: 510 L: 477 D: 1873
Penta | [17, 251, 860, 286, 16]
https://chess.swehosting.se/test/9532/
=> 50mr fix + datagen fix

engine/src/bitboard.h, engine/src/defs.h, engine/src/movegen.h, engine/src/movepick.h, engine/src/patricia.cpp, engine/src/position.h, engine/src/search.h, engine/src/uci.h
Elo   | 8.71 +- 4.14 (95%)
Games | N: 8498 W: 1589 L: 1376 D: 5533
Penta | [95, 836, 2189, 1019, 110]
https://chess.swehosting.se/test/9824/
=> Staged movegen

engine/src/search.h
Bench: 5053873
Elo   | 0.96 +- 1.31 (95%)
LLR   | 0.51 (-2.94, 2.94) [0.00, 3.00]
Games | N: 83172 W: 14753 L: 14522 D: 53897
Penta | [889, 9101, 21328, 9426, 842]
https://chess.swehosting.se/test/10355/
gabe wanted me to merge so i merge
=> 50mr scaling

engine/src/nnue.h, engine/src/position.h, engine/src/search.h
=> reset instead of applying more updates

engine/src/search.h
=> Tweak corrhist

engine/src/search.h
=> Collect all TT info at the beginning

engine/src/movepick.h, engine/src/position.h
=> TT move only once

engine/src/search.h, engine/src/utils.h
Bench: 3048156
Elo   | 2.91 +- 2.09 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 3.00]
Games | N: 31264 W: 5567 L: 5305 D: 20392
Penta | [252, 3437, 8036, 3611, 296]
https://chess.swehosting.se/test/12158/
=> contcorrhist
